version: '3.7'
services:
  app:
    build: .
    container_name: devhub-app
    command: 'npm run start:dev'

    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devhub
    volumes:
      - pgdata:/data/postgres_db
volumes:
  pgdata:
    driver: local
